config/routes.rb
Rails.application.routes.draw do
  root 'tic_tac_toe#new'

  get '/new' => 'tic_tac_toe#new'
  post '/make_move' => 'tic_tac_toe#make_move'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# app/models/board.rb
class Board
  attr_reader :board_arr

  # initialize board
  def initialize(board_arr = nil)
    @board_arr = board_arr || Board.blank_board
  end

  def self.blank_board
    Array.new(3){Array.new(3)}
  end

  def add_piece(coords, piece)
    @board_arr[coords[0]][coords[1]] = piece
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tic_tac_toe_controller.rb
class TicTacToeController < ApplicationController
  def new
    @current_player = 'X'
    @board_arr = Board.new.board_arr

    save_player
    save_board_arr
    render :game_board
  end

  def make_move
    @current_player = retrieve_current_player
    @board = Board.new(retrieve_board_arr)
    @board.add_piece(retrieve_coords, @current_player)

    @board_arr = @board.board_arr
    switch_player
    save_player
    save_board_arr
    render :game_board
  end

  private

  def retrieve_coords
    params[:move].split(",").map(&:to_i)
  end

  def save_board_arr
    session[:saved_board_arr] = @board_arr
  end

  def retrieve_board_arr
    session[:saved_board_arr]
  end

  def switch_player
    @current_player = (@current_player == 'X' ? 'O' : 'X')
  end

  def retrieve_current_player
    session[:current_player]
  end

  def save_player
    session[:current_player] = @current_player
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tic_tac_toe_helper.rb
module TicTacToeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTictactoeRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tic_tac_toe/game_board.html.erb
<h1>Welcome to TicTacToe!</h1>
<h2>It is is player <%= @current_player %>'s turn!</h2>
<p>
  Enter your selection using the form below
</p>


<pre>
  <table>
    <% @board_arr.each do |row| %>
      <tr>
        <% row.each do |cell| %>
          <td>
          <%= cell.nil? ? '-' : cell %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</pre>


<%= form_tag(make_move_path, :method => "POST") do %>
  <table>
    <% 3.times do |row| %>
      <tr>
        <% 3.times do |cell| %>
          <td>
            <%= radio_button_tag("move","#{row},#{cell}") %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= submit_tag "Make Move" %>
<% end %>